version: "3"

services:
    l1-api:
        build: ./
        ports:
            - "3000:3000"
        links:
            - l1-mongo
    l1-mongo:
        image: mongo:5.0.9
        ports:
            - "27017:27017"
